---

version: "3.6"
services:
  db:
    image: "postgres:9.6.9-alpine"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: ./config/.env
    ports:
      - "5432:5432"

  web:
      build:
        target: development_build
        context: .
        dockerfile: ./docker/django/Dockerfile
        args:
          DJANGO_ENV: development
      volumes:
        - django-static:/var/www/django/static
      depends_on:
        - db
      env_file: ./config/.env
      environment:
        DJANGO_DATABASE_HOST: db
    command: python -Wd manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    healthcheck:
      test: curl --fail http://localhost:8000/health/?format=json || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:alpine
    restart: on-failure
    
    ports:
      - "6379:6379"

volumes:
  pgdata:
  django-static:
  django-media:
  django-locale:
