version: 2

workflows:
  version: 2

  build-and-test:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.6
        environment:
          DJANGO_SECRET_KEY: notreallysecret
          DATABASE_URL: postgres://postgres@127.0.0.1:5432/legal-basis
          AUTHBROKER_URL: https://sso.trade.gov.uk/
          AUTHBROKER_CLIENT_ID: client_id
          AUTHBROKER_CLIENT_SECRET: client_secret
          DOMAIN_NAME: trade.gov.uk
          TLS_EMAIL: webmaster@trade.gov.uk

      - image: circleci/postgres:10.11
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: legal-basis

    steps:
      - checkout

      - run:
          name: Configure poetry
          command: poetry config virtualenvs.in-project true

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: Install dependencies
          command: poetry install

      - save_cache:
          paths:
            - ./.venv
          key: v2-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: Run tests
          command: poetry run docker/ci.sh
